admin_fields.settings:
  type: config_object
  label: 'Admin fields settings'
  mapping:
    admin_fields_track:
      type: sequence
      label: 'Configuration for each content_type'
      sequence:
        type: string
        label: 'Content type name'
